name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v4

      - name: 🔧 Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Abhängigkeiten installieren
        run: npm install

      - name: ✅ Tests ausführen
        run: npm test

      - name: 📂 Deployment-Ordner vorbereiten
        run: |
          mkdir -p public
          cp -r src/* public/  # Kopiert alle Dateien aus `src` nach `public`
      
      - name: ⬆️ Build-Artefakt hochladen (neueste Version)
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # artifact name
          path: public        # storage location
          retention-days: 1   # delete the artifact after 1 day (optional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 📥 Artifact herunterladen
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: public

      - name: 🚀 Deployment auf GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
